### ISSUE TITLE
Failure during configure: No such file or directory: third_party/botan/doc/cli.rst

### ISSUE THREAD

**Issue by noughtmare** [ZHaskell/z-botan#17]
I just tried opening a repl with Z-Botan, but I got an error.

Here is the complete log:

```
$ cabal repl -b Z-Botan -j1 --ghc-options=-j1
Resolving dependencies...
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
 - Z-Botan-0.1.1.2 (lib:Z-Botan) (requires build)
 - fake-package-0 (lib) (first run)
[1 of 1] Compiling Main             ( /tmp/cabal-repl.-11114/dist-newstyle/tmp/src-11114/Z-Botan-0.1.1.2/dist/setup/setup.hs, /tmp/cabal-repl.-11114/dist-newstyle/tmp/src-11114/Z-Botan-0.1.1.2/dist/setup/Main.o )
Linking /tmp/cabal-repl.-11114/dist-newstyle/tmp/src-11114/Z-Botan-0.1.1.2/dist/setup/setup ...
Configuring Z-Botan-0.1.1.2...
   INFO: /tmp/cabal-repl.-11114/dist-newstyle/tmp/src-11114/Z-Botan-0.1.1.2/third_party/botan/configure.py invoked with options "--amalgamation --disable-shared --cpu=x86_64 --os=linux"
   INFO: Configuring to build Botan 2.17.0 (revision unknown)
   INFO: Running under 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
   INFO: Autodetected platform information: OS="Linux" machine="x86_64" proc=""
   INFO: Guessing to use compiler gcc (use --cc or CXX to set)
   INFO: Found sphinx-build (use --without-sphinx to disable)
   INFO: Found rst2man (use --without-rst2man to disable)
   INFO: Using /etc/ssl/certs/ca-certificates.crt as system certificate store
   INFO: Auto-detected compiler version 8.3
   INFO: Auto-detected compiler arch x86_64
   INFO: Target is gcc:8.3-linux-x86_64
   INFO: Assuming target x86_64 is little endian
   INFO: Skipping (dependency failure): asio certstor_sqlite3 sessions_sqlite3
   INFO: Skipping (incompatible CPU): aes_armv8 aes_power8 sha1_armv8 sha2_32_armv8 sm4_armv8
   INFO: Skipping (incompatible OS): certstor_system_macos certstor_system_windows commoncrypto getentropy win32_stats
   INFO: Skipping (no enabled compression schemes): compression
   INFO: Skipping (requires external dependency): boost bzip2 lzma openssl sqlite3 tpm zlib
   INFO: Loading modules: adler32 aead aes aes_ni aes_vperm aont argon2 aria asn1 auto_rng base base32 base58 base64 bcrypt bcrypt_pbkdf bigint blake2 block blowfish camellia cascade cast128 cast256 cbc cbc_mac ccm cecpq1 certstor_flatfile certstor_sql certstor_system cfb chacha chacha20poly1305 chacha_avx2 chacha_rng chacha_simd32 checksum cmac comb4p cpuid crc24 crc32 cryptobox ctr curve25519 des dev_random dh dl_algo dl_group dlies dsa dyn_load eax ec_group ecc_key ecdh ecdsa ecgdsa ecies eckcdsa ed25519 elgamal eme_oaep eme_pkcs1 eme_raw emsa1 emsa_pkcs1 emsa_pssr emsa_raw emsa_x931 entropy fd_unix ffi filters fpe_fe1 gcm ghash ghash_cpu ghash_vperm gmac gost_28147 gost_3410 gost_3411 hash hash_id hex hkdf hmac hmac_drbg hotp http_util idea idea_sse2 iso9796 kasumi kdf kdf1 kdf1_iso18033 kdf2 keccak keypair lion locking_allocator mac mce mceies md4 md5 mdx_hash mem_pool mgf1 misty1 mode_pad modes mp newhope nist_keywrap noekeon noekeon_simd numbertheory ocb ofb par_hash passhash9 pbes2 pbkdf pbkdf1 pbkdf2 pem pgp_s2k pk_pad pkcs11 poly1305 poly_dbl prf_tls prf_x942 proc_walk processor_rng psk_db pubkey rc4 rdrand_rng rdseed rfc3394 rfc6979 rmd160 rng roughtime rsa salsa20 scrypt seed serpent serpent_avx2 serpent_simd sessions_sql sha1 sha1_sse2 sha1_x86 sha2_32 sha2_32_bmi2 sha2_32_x86 sha2_64 sha2_64_bmi2 sha3 sha3_bmi2 shacal2 shacal2_avx2 shacal2_simd shacal2_x86 shake shake_cipher simd simd_avx2 siphash siv skein sm2 sm3 sm4 socket sodium sp800_108 sp800_56a sp800_56c srp6 stateful_rng stream streebog system_rng thread_utils threefish_512 threefish_512_avx2 tiger tls tls_10 tls_cbc tss twofish utils uuid whirlpool x509 x919_mac xmss xtea xts
   INFO: Using symlink to link files into build dir (use --link-method to change)
   INFO: Writing amalgamation header to botan_all.h
   INFO: Writing amalgamation source to botan_all.cpp
  ERROR: Traceback (most recent call last):
  File "/tmp/cabal-repl.-11114/dist-newstyle/tmp/src-11114/Z-Botan-0.1.1.2/third_party/botan/configure.py", line 3389, in <module>
    sys.exit(main(argv=sys.argv))
  File "/tmp/cabal-repl.-11114/dist-newstyle/tmp/src-11114/Z-Botan-0.1.1.2/third_party/botan/configure.py", line 3383, in main
    do_io_for_build(cc, arch, osinfo, using_mods, build_paths, source_paths, template_vars, options)
  File "/tmp/cabal-repl.-11114/dist-newstyle/tmp/src-11114/Z-Botan-0.1.1.2/third_party/botan/configure.py", line 3242, in do_io_for_build
    cli_doc_contents = open(cli_doc).readlines()
IOError: [Errno 2] No such file or directory: '/tmp/cabal-repl.-11114/dist-newstyle/tmp/src-11114/Z-Botan-0.1.1.2/third_party/botan/doc/cli.rst'

An internal error occurred.

Don't panic, this is probably not your fault! Please open an issue
with the entire output at https://github.com/randombit/botan

You'll meet friendly people happy to help!
cabal: Failed to build Z-Botan-0.1.1.2 (which is required by fake-package-0).
The failure occurred during the configure step.
```

**Comment by winterland1989** [comment]
Could be the missing of rst files in cabal cause this. On my ubuntu `cabal repl -b` goes just fine, could you tell me what's your platform?

**Comment by winterland1989** [comment]
I uploaded a new release v0.2 to hackage to include the docs, could you please update the cabal index and try again?

**Comment by noughtmare** [comment]
I am using Debian 10 buster. But v0.2 works for me, thanks!
